<a href="https://colab.research.google.com/github/coldbilberry/repo-gui/blob/main/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_%D0%B2%D1%8B%D1%81%D1%88%D1%83%D1%8E_%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D1%83.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1)



In [1]:
import numpy as np
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
B = np.array([12,2,1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

2)

In [2]:
A = np.array([[1,2,-1],[3,-4,0],[8,-5,2],[2,-5,0],[11,4,-7]])
B = np.array([1,7,12,7,15])
np.linalg.lstsq(A, B)

<ipython-input-2-eb77974e94c3>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.15601029, -0.889718  , -0.85029782]),
 array([0.66772534]),
 3,
 array([14.89650167, 10.4695886 ,  2.73531577]))

3)

In [3]:
a = np.array([[1,2,3], [4,0,6],[7,8,9]])
b = np.array([12,2,1])
print(np.linalg.solve(a, b))
np.linalg.lstsq(a, b)

[-9.2         0.9         6.46666667]


<ipython-input-3-e8f5e288f498>:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(a, b)


(array([-9.2       ,  0.9       ,  6.46666667]),
 array([], dtype=float64),
 3,
 array([15.63376871,  3.81768041,  1.00528221]))

In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([2,5,1])
print(np.linalg.solve(a, b))
np.linalg.lstsq(a, b)

LinAlgError: Singular matrix

4)

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

a = np.array([[1,2,3],[2,16,21],[4,28,73]])
P, L, U = scipy.linalg.lu(a)
print(P)
print(L)
print(U)
print(np.dot(P, a) - np.dot(L, U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[ -2. -12. -52.]
 [  3.  26.  70.]
 [ -1. -14. -18.]]


In [7]:
a = np.array([[1,2,3],[2,16,21],[4,28,73]])
b = np.array([1,2,3])
np.linalg.solve(a, b)

array([ 1.01388889,  0.03472222, -0.02777778])

5)

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg
from pylab import *
from mpl_toolkits.mplot3d import Axes3D

In [9]:
def Q(x, y, z):
    return np.sqrt(x**2 + y**2 + z**2)

In [10]:
fig2 = figure()
ax = Axes3D(fig2)
X = np.arange(-5, 5, 0.5)
Y = np.arange(-5, 5, 0.5)
X, Y = np.meshgrid(X, Y)
ax.plot_surface(X, Y, Q(X, Y, X + 2*Y - 1))
ax.plot_surface(X, Y, Q(X, Y, 12 - 8*X+5*Y))
ax.scatter(0,0,0,'z',50,'red')
show()
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])
print(f'Ответ: {np.linalg.lstsq(A,B, rcond=-1)}')

<Figure size 640x480 with 0 Axes>

Ответ: (array([ 1.38191882, -0.18081181,  0.0202952 ]), array([], dtype=float64), 2, array([9.65316119, 2.41173777]))


6)

In [11]:
import numpy as np
import scipy.linalg
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([2,5,11])
Q, R = np.linalg.qr(A)
print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [12]:
print(np.dot(Q, R))
print(np.dot(np.transpose(Q), Q))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.00000000e+00 -2.48218629e-16 -2.62094065e-17]
 [-2.48218629e-16  1.00000000e+00  2.82872043e-17]
 [-2.62094065e-17  2.82872043e-17  1.00000000e+00]]


In [13]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [14]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  3.55271368e-15])

In [15]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 3.92767275e-15])

In [16]:
X = np.append(X1, 0)
print(X)               # псевдорешение для исходной системы
np.linalg.norm(X)

[1.50000000e+00 3.92767275e-15 0.00000000e+00]


1.499999999999996

In [17]:
np.linalg.norm(np.dot(A, X) - B)   # невязка системы

1.224744871391589