<a href="https://colab.research.google.com/github/coldbilberry/repo-gui/blob/main/%D0%9B%D0%B8%D0%BD_%D0%B0%D0%BB%D0%B3_%D1%83%D1%80%D0%BE%D0%BA2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Задание 2.1

In [10]:
A = np.matrix([[1, -2],
              [3, 0]])
B = np.matrix([[4, -1],
               [0, 5]])

In [11]:
A + B

matrix([[ 5, -3],
        [ 3,  5]])

In [12]:
A.dot(B)

matrix([[  4, -11],
        [ 12,  -3]])

Задание 3.1

In [7]:
A = np.matrix([[1, 7],
               [3, -6]])
B = np.matrix([[0, 5],
               [2, -1]])
C = np.matrix([[2, -4],
               [1, -1]])

In [8]:
3*A, 2*B, 4*C

(matrix([[  3,  21],
         [  9, -18]]), matrix([[ 0, 10],
         [ 4, -2]]), matrix([[  8, -16],
         [  4,  -4]]))

In [9]:
3*A - 2*B + 4*C

matrix([[ 11,  -5],
        [  9, -20]])

Задание 4.1

In [13]:
A = np.matrix([[4, 1],
               [5, -2],
               [2, 3]])

In [14]:
A.T

matrix([[ 4,  5,  2],
        [ 1, -2,  3]])

In [16]:
A.dot(A.T)

matrix([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]])

In [17]:
A.T.dot(A)

matrix([[45,  0],
        [ 0, 14]])

Задание 1.2

a)



In [19]:
x = 1
A = np.matrix([[np.sin(x), -np.cos(x)],
               [np.cos(x), np.sin(x)]])
np.linalg.det(A)

1.0

б)

In [20]:
A = np.matrix([[4, 2, 3],
               [0, 5, 1],
               [0, 0, 9]])
np.linalg.det(A)

180.0

в)

In [21]:
A = np.matrix([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
np.linalg.det(A)

0.0

Задание 4.2

а)

In [22]:
A = np.matrix([[1, 2, 3],
               [1, 1, 1],
               [2, 3, 4]])
np.linalg.matrix_rank(A)

2

б)

In [23]:
A = np.matrix([[0, 0, 2, 1],
               [0, 0, 2, 2],
               [2, 3, 5, 6]])
np.linalg.matrix_rank(A)

3