<a href="https://colab.research.google.com/github/coldbilberry/repo-gui/blob/main/%D0%A3%D1%80%D0%BE%D0%BA4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import scipy as sp

Задание 1

a)

In [ ]:
A = np.array([[1, -2], [3, -4]])

In [ ]:
np.linalg.det(A)

2.0000000000000004

In [ ]:
A1 = np.array([[1, 7], [3, -4]])
A2 = np.array([[1, -2], [1, 7]])

In [ ]:
x1 = np.linalg.det(A1) / np.linalg.det(A)
x2 = np.linalg.det(A2) / np.linalg.det(A)

In [ ]:
print(f'x1 = {x1}\nx2 = {x2}\n')

x1 = -12.5
x2 = 4.5



б)

In [ ]:
A = np.array([[2, -1, 5], [1, -1, -3], [2, 4, 1]])

In [ ]:
np.linalg.det(A)

58.999999999999964

In [ ]:
A1 = np.array([[10, -2, 1], [1, -1, -3], [2, 4, 1]])
A2 = np.array([[2, -1, 5], [10, -2, 1], [2, 4, 1]])
A3 = np.array([[2, -1, 5], [1, -1, -3], [10, -2, 1]])

In [ ]:
np.linalg.det(A1)

130.00000000000009

In [ ]:
x1 = np.linalg.det(A1) / np.linalg.det(A)
x2 = np.linalg.det(A2) / np.linalg.det(A)
x3 = np.linalg.det(A3) / np.linalg.det(A)

In [ ]:
print(f'x1 = {x1}\nx2 = {x2}\nx3 = {x3}')

x1 = 2.203389830508477
x2 = 3.6610169491525455
x3 = 0.966101694915255


Задание 2

In [1]:
from scipy.linalg import lu

In [8]:
A = np.array([[1, 2, 4,], [2, 9, 12], [3, 26, 30]])
A

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

In [9]:
print(f'L = \n\n{lu(A)[1]}')

L = 

[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]


б)

In [11]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
A

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

In [12]:
print(f'L = \n\n{lu(A)[1]}')

L = 

[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75       -0.25        1.          0.        ]
 [ 0.25        0.75       -0.17073171  1.        ]]


Задание 3

In [14]:
from scipy.linalg import lu_factor, lu_solve

In [15]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
A

array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])

In [16]:
b = np.array([1, -6, -5])

In [17]:
lu, piv = lu_factor(A)

In [18]:
x = lu_solve((lu, piv), b)

In [20]:
print(f'x1 = {x[0]}\nx2 = {x[1]}\nx3 = {x[2]}')

x1 = -1.0
x2 = 0.0
x3 = 1.0


Задание 4

In [21]:
from scipy.linalg import cho_factor, cho_solve, cholesky

In [22]:
A = ([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
A

[[81, -45, 45], [-45, 50, -15], [45, -15, 38]]

In [23]:
b = np.array([531, -460, 193])

In [24]:
c, low = cho_factor(A)

In [25]:
x = cho_solve((c, low), b)

In [26]:
print(f'x1 = {x[0]}\nx2 = {x[1]}\nx3 = {x[2]}')

x1 = 6.0
x2 = -5.0
x3 = -4.0
