In [1]:
import torch

In [2]:
float_tensor = torch.randn(3, 4, 5).float()
float_tensor

tensor([[[ 0.8040, -0.2667, -0.6851,  0.9533,  0.5229],
         [-0.6453, -0.8575,  0.9305, -0.4348,  0.6981],
         [-1.0953, -0.0470,  1.4930,  0.6138,  1.9125],
         [-0.7216, -0.2286,  0.9756, -1.6038,  1.0932]],

        [[-1.2503,  0.2824,  2.1230, -1.6451,  0.2218],
         [ 1.7807, -0.7512, -1.1283,  1.8010,  0.1822],
         [-0.6313,  0.5952,  1.2716,  1.3894, -1.1944],
         [ 1.2623,  1.0014,  0.6662, -0.1170,  0.7069]],

        [[ 1.2023, -0.5731, -1.4844,  0.5724,  0.2819],
         [-0.9629,  1.1292,  1.1355, -0.0940, -0.5612],
         [ 1.0840,  0.2294, -0.5911,  0.0276,  0.3364],
         [-0.7263,  0.4304, -1.0646,  0.2920,  0.1704]]])

In [3]:
float_tensor.shape

torch.Size([3, 4, 5])

In [5]:
float_tensor = float_tensor.reshape(6, 10)
float_tensor.size()

torch.Size([6, 10])

In [6]:
int_tensor = torch.randn(10).int()
int_tensor

tensor([ 0, -3,  1,  0,  0,  0,  0,  0,  0,  2], dtype=torch.int32)

In [7]:
float_tensor * int_tensor

tensor([[ 0.0000,  0.8002, -0.6851,  0.0000,  0.0000, -0.0000, -0.0000,  0.0000,
         -0.0000,  1.3963],
        [-0.0000,  0.1409,  1.4930,  0.0000,  0.0000, -0.0000, -0.0000,  0.0000,
         -0.0000,  2.1864],
        [-0.0000, -0.8472,  2.1230, -0.0000,  0.0000,  0.0000, -0.0000, -0.0000,
          0.0000,  0.3644],
        [-0.0000, -1.7856,  1.2716,  0.0000, -0.0000,  0.0000,  0.0000,  0.0000,
         -0.0000,  1.4137],
        [ 0.0000,  1.7194, -1.4844,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000,
         -0.0000, -1.1225],
        [ 0.0000, -0.6882, -0.5911,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000,
          0.0000,  0.3407]])

In [8]:
mm_tensor = float_tensor.mm(float_tensor.T)
mm_tensor.shape

torch.Size([6, 6])

In [9]:
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)

y = (x**3) + z - 75 * t
y.backward()
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [10]:
nm_tensor = torch.randn(5, 6)

In [11]:
nm_tensor.numpy()

array([[-0.41840145, -0.09671415,  1.0270312 ,  0.350005  , -0.1661472 ,
        -1.9732461 ],
       [-0.58211434, -0.20337272, -0.16452348, -0.30767843, -0.87950706,
         1.0869808 ],
       [-0.06159718,  1.7104483 , -0.14320713,  0.1687928 ,  0.04371179,
        -0.15635161],
       [ 1.3758911 , -2.7237659 ,  0.15666479,  0.6283014 ,  0.41169742,
         0.34513214],
       [-1.3362918 , -0.02792919,  0.98655707, -0.14102428, -0.41896558,
         0.31942388]], dtype=float32)